export enum Permission {
  // User permissions
  USER_CREATE = 'USER_CREATE',
  USER_VIEW = 'USER_VIEW',
  USER_EDIT = 'USER_EDIT',
  USER_DELETE = 'USER_DELETE',
  USER_MANAGE_ROLES = 'USER_MANAGE_ROLES',

  // Role permissions
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_VIEW = 'ROLE_VIEW',
  ROLE_EDIT = 'ROLE_EDIT',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_MANAGE_PERMISSIONS = 'ROLE_MANAGE_PERMISSIONS',

  // Asset permissions
  ASSET_CREATE = 'ASSET_CREATE',
  ASSET_VIEW = 'ASSET_VIEW',
  ASSET_EDIT = 'ASSET_EDIT',
  ASSET_DELETE = 'ASSET_DELETE',

  // Work Order permissions
  WORKORDER_CREATE = 'WORKORDER_CREATE',
  WORKORDER_VIEW = 'WORKORDER_VIEW',
  WORKORDER_EDIT = 'WORKORDER_EDIT',
  WORKORDER_DELETE = 'WORKORDER_DELETE',

  // Inventory permissions
  INVENTORY_CREATE = 'INVENTORY_CREATE',
  INVENTORY_VIEW = 'INVENTORY_VIEW',
  INVENTORY_EDIT = 'INVENTORY_EDIT',
  INVENTORY_DELETE = 'INVENTORY_DELETE',

  // Purchase permissions
  PURCHASE_CREATE = 'PURCHASE_CREATE',
  PURCHASE_VIEW = 'PURCHASE_VIEW',
  PURCHASE_EDIT = 'PURCHASE_EDIT',
  PURCHASE_DELETE = 'PURCHASE_DELETE',

  // Report permissions
  REPORT_CREATE = 'REPORT_CREATE',
  REPORT_VIEW = 'REPORT_VIEW',
  REPORT_EDIT = 'REPORT_EDIT',
  REPORT_DELETE = 'REPORT_DELETE',

  // Admin permissions
  ADMIN_ACCESS = 'ADMIN_ACCESS'
}
